# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

# MixedReality-WebRTC build pipeline for Release
# Build the core WebRTC implementation and the UWP wrappers

# Disable branch and PR triggers, the core implementation only changes
# when upgrading to a more recent version from Google, which is quite
# infrequent. Also this pipeline is very long (several hours) so should
# be triggered manually only when needed.
trigger: none
pr: none

# Give a unique name to the build each time it runs
name: $(Date:yyyyMMdd)-$(Rev:r)

stages:

# Compile all platform/architecture/config variants as separate jobs
# possibly in parallel if enough agents are available
- stage: build
  displayName: Build Core WebRTC
  jobs:
  - template: templates/jobs-libwebrtc-win32.yaml
    parameters:
      buildAgent: $(BuildAgent)
      buildArch: 'x86'
      buildConfig: 'Debug'
  - template: templates/jobs-libwebrtc-win32.yaml
    parameters:
      buildAgent: $(BuildAgent)
      buildArch: 'x64'
      buildConfig: 'Debug'
  - template: templates/jobs-libwebrtc-uwp.yaml
    parameters:
      buildAgent: $(BuildAgent)
      buildArch: 'x86'
      buildConfig: 'Debug'
      publishWinRtHeaders: true # Randomly selected, any UWP build will do
  - template: templates/jobs-libwebrtc-uwp.yaml
    parameters:
      buildAgent: $(BuildAgent)
      buildArch: 'x64'
      buildConfig: 'Debug'
  - template: templates/jobs-libwebrtc-uwp.yaml
    parameters:
      buildAgent: $(BuildAgent)
      buildArch: 'ARM'
      buildConfig: 'Debug'
  # - template: templates/jobs-libwebrtc-uwp.yaml
  #   parameters:
  #     buildAgent: $(BuildAgent)
  #     buildArch: 'ARM64'
  #     buildConfig: 'Debug'
  - template: templates/jobs-libwebrtc-win32.yaml
    parameters:
      buildAgent: $(BuildAgent)
      buildArch: 'x86'
      buildConfig: 'Release'
  - template: templates/jobs-libwebrtc-win32.yaml
    parameters:
      buildAgent: $(BuildAgent)
      buildArch: 'x64'
      buildConfig: 'Release'
  - template: templates/jobs-libwebrtc-uwp.yaml
    parameters:
      buildAgent: $(BuildAgent)
      buildArch: 'x86'
      buildConfig: 'Release'
  - template: templates/jobs-libwebrtc-uwp.yaml
    parameters:
      buildAgent: $(BuildAgent)
      buildArch: 'x64'
      buildConfig: 'Release'
  - template: templates/jobs-libwebrtc-uwp.yaml
    parameters:
      buildAgent: $(BuildAgent)
      buildArch: 'ARM'
      buildConfig: 'Release'
  # - template: templates/jobs-libwebrtc-uwp.yaml
  #   parameters:
  #     buildAgent: $(BuildAgent)
  #     buildArch: 'ARM64'
  #     buildConfig: 'Release'
