# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See LICENSE in the project root for license information.

# MixedReality-WebRTC build pipeline for documentation CI
# Build the user manual and API reference from the sources

# Trigger CI on push changes
trigger:
  branches:
    include:
    - master
    - dev
    exclude:
    - docs/*
  paths:
    include:
    - docs/*

# Do not trigger CI on PRs
pr: none

# Give a unique name to the build each time it runs
name: ci-docs-$(SourceBranchName)-$(Date:yyyyMMdd)-$(Rev:r)

jobs:
- template: templates/jobs-docs.yaml
  parameters:
    buildAgent: 'MR Sharing On-Prem'
