# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

# [TEMPLATE] Compile WebRTC Core for Desktop (Win32) platform

parameters:
  buildAgent: ''
  buildArch: ''        # x86|x64
  buildConfig: ''      # Debug|Release

jobs:

# Compile webrtc.lib (core Google implementation)
- job: libwebrtc_Win32_${{parameters.buildArch}}_${{parameters.buildConfig}}
  timeoutInMinutes: 360
  pool:
    name: ${{parameters.buildAgent}}
    demands:
    - msbuild
  variables:
    buildTriple: Win32-${{parameters.buildArch}}-${{parameters.buildConfig}}
    projectRoot: 'external/webrtc-uwp-sdk/webrtc/windows/projects/msvc/'
  steps:

  # Install Python 2.7.17 and select as default
  - template: 'steps-install-python2x.yaml'
    parameters:
      tempFolder: '$(Build.BinariesDirectory)\py27'
      pythonVersion: '2.7.17'

  # Checkout
  - checkout: self
    submodules: recursive
    clean: $(clean.git)

  # Compute the PDB package variables
  - task: PowerShell@2
    displayName: 'Compute PDB package variables'
    inputs:
      targetType: filePath
      filePath: tools/ci/computePdbPackageVars.ps1
    env:
      # Compute and write $(MRWebRTC_PdbPackageVersion) from build pipeline variables
      WRITE_VERSION: 'true'

  # Map build* variables to script* ones
  - task: PowerShell@2
    displayName: Map script variables
    inputs:
      targetType: filePath
      filePath: tools/ci/mapVariables.ps1
      arguments: 'Win32 ${{parameters.buildArch}} ${{parameters.buildConfig}}'

  # Prepare build
  - task: PythonScript@0
    displayName: 'Prepare build'
    inputs:
      scriptSource: 'filePath'
      scriptPath: 'external/webrtc-uwp-sdk/scripts/run.py'
      arguments: '-a prepare -t webrtc -p win --cpus $(scriptArch) -c $(scriptConfig) --noColor --noWrapper'
      failOnStderr: false

  # Clean-up unused files
  - script: |
      del /F /S /Q "depot_tools/external_bin/gsutil"
      del /F /S /Q "chromium/third_party/protobuf/java"
      del /F /S /Q "chromium/tools/android"
      del /F /S /Q "chromium/tools/code_coverage"
    workingDirectory: 'external/webrtc-uwp-sdk/webrtc/xplatform'
    displayName: 'Clean-up unused files'

  # Run component detection
  - task: ms.vss-governance-buildtask.governance-build-task-component-detection.ComponentGovernanceComponentDetection@0
    displayName: 'Component Detection'
    #inputs:
      #scanType: 'LogOnly'
      #sourceScanPath: '$(sourcesRoot)'

  # Build webrtc.lib
  - task: PythonScript@0
    displayName: 'Build webrtc.lib ($(buildTriple))'
    inputs:
      scriptSource: 'filePath'
      scriptPath: 'external/webrtc-uwp-sdk/scripts/run.py'
      arguments: '-a build -t webrtc -p win --cpus $(scriptArch) -c $(scriptConfig) --noColor --noWrapper'
      failOnStderr: false
    timeoutInMinutes: 120

  # Publish webrtc.lib as pipeline artifacts (limited retention)
  - task: PublishPipelineArtifact@0
    displayName: 'Publish webrtc.lib ($(buildTriple))'
    inputs:
      artifactName: 'libwebrtc_$(buildTriple)'
      targetPath: 'external/webrtc-uwp-sdk/webrtc/xplatform/webrtc/OUTPUT/webrtc/$(scriptPlatform)/${{parameters.buildArch}}/${{parameters.buildConfig}}/webrtc.lib'
    timeoutInMinutes: 15

  # Publish PDBs for webrtc.lib as pipeline artifacts (limited retention)
  # - task: PublishPipelineArtifact@0
  #   displayName: 'Publish PDBs for webrtc.lib ($(buildTriple))'
  #   inputs:
  #     artifactName: 'libwebrtc_pdbs_$(buildTriple)'
  #     targetPath: 'external/webrtc-uwp-sdk/webrtc/xplatform/webrtc/OUTPUT/webrtc/$(scriptPlatform)/${{parameters.buildArch}}/${{parameters.buildConfig}}/pdbs'
  #   timeoutInMinutes: 15

  # Publish PDBs for webrtc.lib as Universal Package (unlimited retention)
  - task: UniversalPackages@0
    displayName: 'Publish PDBs for webrtc.lib ($(buildTriple))'
    inputs:
      command: publish
      publishDirectory: 'external/webrtc-uwp-sdk/webrtc/xplatform/webrtc/OUTPUT/webrtc/$(scriptPlatform)/${{parameters.buildArch}}/${{parameters.buildConfig}}/pdbs'
      vstsFeedPublish: $(MRWebRTC_PdbFeed)
      vstsFeedPackagePublish: $(MRWebRTC_PdbPackageName)
      versionOption: custom
      versionPublish: $(MRWebRTC_PdbPackageVersion)
      packagePublishDescription: 'PDBs for MixedReality-WebRTC core (webrtc.lib) $(buildTriple)'
    timeoutInMinutes: 30



