# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: access_measurements.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19\x61\x63\x63\x65ss_measurements.proto\x12\x06\x61\x63\x63\x65ss\"\x0c\n\nGetRequest\"\x1b\n\nSetRequest\x12\r\n\x05value\x18\x01 \x01(\x02\"\x16\n\x05Reply\x12\r\n\x05value\x18\x01 \x01(\x02\x32\xcb\x02\n\tSetGetter\x12\x34\n\rGetAngleHzRad\x12\x12.access.GetRequest\x1a\r.access.Reply\"\x00\x12\x33\n\x0cGetAngleVRad\x12\x12.access.GetRequest\x1a\r.access.Reply\"\x00\x12\x33\n\x0cGetDistSlope\x12\x12.access.GetRequest\x1a\r.access.Reply\"\x00\x12\x34\n\rSetAngleHzRad\x12\x12.access.SetRequest\x1a\r.access.Reply\"\x00\x12\x33\n\x0cSetAngleVRad\x12\x12.access.SetRequest\x1a\r.access.Reply\"\x00\x12\x33\n\x0cSetDistSlope\x12\x12.access.SetRequest\x1a\r.access.Reply\"\x00\x42\x36\n$io.grpc.examples.access_measurementsB\x06\x61\x63\x63\x65ssP\x01\xa2\x02\x03\x41MSb\x06proto3')



_GETREQUEST = DESCRIPTOR.message_types_by_name['GetRequest']
_SETREQUEST = DESCRIPTOR.message_types_by_name['SetRequest']
_REPLY = DESCRIPTOR.message_types_by_name['Reply']
GetRequest = _reflection.GeneratedProtocolMessageType('GetRequest', (_message.Message,), {
  'DESCRIPTOR' : _GETREQUEST,
  '__module__' : 'access_measurements_pb2'
  # @@protoc_insertion_point(class_scope:access.GetRequest)
  })
_sym_db.RegisterMessage(GetRequest)

SetRequest = _reflection.GeneratedProtocolMessageType('SetRequest', (_message.Message,), {
  'DESCRIPTOR' : _SETREQUEST,
  '__module__' : 'access_measurements_pb2'
  # @@protoc_insertion_point(class_scope:access.SetRequest)
  })
_sym_db.RegisterMessage(SetRequest)

Reply = _reflection.GeneratedProtocolMessageType('Reply', (_message.Message,), {
  'DESCRIPTOR' : _REPLY,
  '__module__' : 'access_measurements_pb2'
  # @@protoc_insertion_point(class_scope:access.Reply)
  })
_sym_db.RegisterMessage(Reply)

_SETGETTER = DESCRIPTOR.services_by_name['SetGetter']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n$io.grpc.examples.access_measurementsB\006accessP\001\242\002\003AMS'
  _GETREQUEST._serialized_start=37
  _GETREQUEST._serialized_end=49
  _SETREQUEST._serialized_start=51
  _SETREQUEST._serialized_end=78
  _REPLY._serialized_start=80
  _REPLY._serialized_end=102
  _SETGETTER._serialized_start=105
  _SETGETTER._serialized_end=436
# @@protoc_insertion_point(module_scope)
