name: e2e-prod-monitoring-test
on:
  schedule:
    - cron: '5 * * * *'
concurrency:
  group: e2e-prod-monitoring-test
  cancel-in-progress: true
jobs:
  run-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./e2e
    steps:
      - name: checkout web-wallet
        uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: '14.x'

      - name: install latest npm
        run: npm install -g npm@latest

      - name: install npm modules
        run: npm i

      - name: clean previous test results
        run: rm -rf ./test-results/

      - name: run tests
        run: CI=true LOG_LEVEL=debug ENVIRONMENT=prod NETWORK=testnet npm run prod-monitoring-test

      - name: upload artifacts
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: test-report
          path: |
            e2e/test-report/
          retention-days: 7
