# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

# [TEMPLATE] Compile WebRTC Core and UWP wrappers for UWP platform

parameters:
  buildAgent: ''
  buildArch: ''               # x86|x64|ARM|ARM64
  buildConfig: ''             # Debug|Release
  publishWinRtHeaders: false  # true|false

jobs:

# Compile webrtc.lib (core Google implementation)
- job: libwebrtc_UWP_${{parameters.buildArch}}_${{parameters.buildConfig}}
  timeoutInMinutes: 360
  pool:
    name: ${{parameters.buildAgent}}
    demands:
    - msbuild
  variables:
    buildTriple: UWP-${{parameters.buildArch}}-${{parameters.buildConfig}}
    projectRoot: 'external/webrtc-uwp-sdk/webrtc/windows/projects/msvc/'
  steps:

  # Install Python 2.7.17 and select as default
  - template: 'steps-install-python2x.yaml'
    parameters:
      tempFolder: '$(Build.BinariesDirectory)\py27'
      pythonVersion: '2.7.17'

  # Checkout
  - checkout: self
    submodules: recursive
    clean: $(clean.git)

  # Compute the PDB package variables
  - task: PowerShell@2
    displayName: 'Compute PDB package variables'
    inputs:
      targetType: filePath
      filePath: tools/ci/computePdbPackageVars.ps1
    env:
      # Compute and write $(MRWebRTC_PdbPackageVersion) from build pipeline variables
      WRITE_VERSION: 'true'

  # Map build* variables to script* ones
  - task: PowerShell@2
    displayName: Map script variables
    inputs:
      targetType: filePath
      filePath: tools/ci/mapVariables.ps1
      arguments: 'UWP ${{parameters.buildArch}} ${{parameters.buildConfig}}'

  # Clean IDLs
  - task: PythonScript@0
    displayName: Clean IDLs
    condition: variables['clean.idls']
    inputs:
      scriptSource: 'filePath'
      scriptPath: 'external/webrtc-uwp-sdk/scripts/run.py'
      arguments: '-a clean --cleanOptions cleanidls'
      failOnStderr: false

  # Restore any NuGet package (C++/WinRT, ...)
  - task: 333b11bd-d341-40d9-afcf-b32d5ce6f23b@2  # NuGetCommand@2
    displayName: 'Restore NuGet packages for Org.WebRtc'
    inputs:
      command: restore
      restoreSolution: '$(projectRoot)Org.WebRtc.Universal/packages.config'
      restoreDirectory: ../../../solutions/packages
    timeoutInMinutes: 10

  # Prepare build
  - task: PythonScript@0
    displayName: 'Prepare build'
    inputs:
      scriptSource: 'filePath'
      scriptPath: 'external/webrtc-uwp-sdk/scripts/run.py'
      arguments: '-a prepare -t webrtc -p winuwp --cpus $(scriptArch) -c $(scriptConfig) --noColor --noWrapper'
      failOnStderr: false

  # Clean-up unused files
  - script: |
      del /F /S /Q "depot_tools/external_bin/gsutil"
      del /F /S /Q "chromium/third_party/protobuf/java"
      del /F /S /Q "chromium/tools/android"
      del /F /S /Q "chromium/tools/code_coverage"
    workingDirectory: 'external/webrtc-uwp-sdk/webrtc/xplatform'
    displayName: 'Clean-up unused files'

  # Run component detection
  - task: ms.vss-governance-buildtask.governance-build-task-component-detection.ComponentGovernanceComponentDetection@0
    displayName: 'Component Detection'
    #inputs:
      #scanType: 'LogOnly'
      #sourceScanPath: '$(sourcesRoot)'

  # Build webrtc.lib
  - task: PythonScript@0
    displayName: 'Build webrtc.lib ($(buildTriple))'
    inputs:
      scriptSource: 'filePath'
      scriptPath: 'external/webrtc-uwp-sdk/scripts/run.py'
      arguments: '-a build -t webrtc -p winuwp --cpus $(scriptArch) -c $(scriptConfig) --noColor --noWrapper'
      failOnStderr: false
    timeoutInMinutes: 120

  # Build the UWP wrapper
  - task: MSBuild@1
    displayName: 'Build Org.WebRTC WinRT wrappers ($(buildTriple))'
    inputs:
      solution: '$(projectRoot)Org.WebRtc.Universal/Org.WebRtc.vcxproj'
      msbuildVersion: '15.0'
      msbuildArchitecture: x64
      platform: ${{parameters.buildArch}}
      configuration: ${{parameters.buildConfig}}
    timeoutInMinutes: 180

  # Publish webrtc.lib as pipeline artifacts (limited retention)
  - task: PublishPipelineArtifact@0
    displayName: 'Publish webrtc.lib ($(buildTriple))'
    inputs:
      artifactName: 'libwebrtc_$(buildTriple)'
      targetPath: 'external/webrtc-uwp-sdk/webrtc/xplatform/webrtc/OUTPUT/webrtc/$(scriptPlatform)/${{parameters.buildArch}}/${{parameters.buildConfig}}/webrtc.lib'
    timeoutInMinutes: 15

  # # Publish PDBs for webrtc.lib as pipeline artifacts (limited retention)
  # - task: PublishPipelineArtifact@0
  #   displayName: 'Publish PDBs for webrtc.lib ($(buildTriple))'
  #   inputs:
  #     artifactName: 'libwebrtc_pdbs_$(buildTriple)'
  #     targetPath: 'external/webrtc-uwp-sdk/webrtc/xplatform/webrtc/OUTPUT/webrtc/$(scriptPlatform)/${{parameters.buildArch}}/${{parameters.buildConfig}}/pdbs'
  #   timeoutInMinutes: 15

  # Publish Org.WebRtc.dll and associated (PDB, ...)
  - task: PublishPipelineArtifact@0
    displayName: 'Publish WinRT wrappers ($(buildTriple))'
    inputs:
      artifactName: 'orgwebrtc_$(buildTriple)'
      targetPath: 'external/webrtc-uwp-sdk/webrtc/windows/projects/msvc/Org.WebRtc.Universal/Build/Output/Org.WebRtc/${{parameters.buildConfig}}/${{parameters.buildArch}}'
    timeoutInMinutes: 15

  # Publish Org.WebRtc generated headers
  - task: PublishPipelineArtifact@0
    displayName: 'Publish WinRT generated headers ($(buildTriple))'
    condition: eq('${{parameters.publishWinRtHeaders}}', 'true')
    inputs:
      artifactName: 'orgwebrtc_headers'
      targetPath: 'external/webrtc-uwp-sdk/webrtc/xplatform/webrtc/sdk/windows/wrapper'
    timeoutInMinutes: 15

  # Publish Org.WebRtc.WrapperGlue.lib and associated (PDB, ...)
  - task: PublishPipelineArtifact@0
    displayName: 'Publish WinRT glue wrappers ($(buildTriple))'
    inputs:
      artifactName: 'orgwebrtc_glue_$(buildTriple)'
      targetPath: 'external/webrtc-uwp-sdk/webrtc/windows/projects/msvc/Org.WebRtc.WrapperGlue.Universal/Build/Output/Org.WebRtc.WrapperGlue/${{parameters.buildConfig}}/${{parameters.buildArch}}'
    timeoutInMinutes: 15

  # Copy all PDBs to a single directory for package publishing
  - task: PowerShell@2
    displayName: Copy PDBs for packaging
    inputs:
      targetType: filePath
      filePath: tools/ci/copyPdbsForPackaging.ps1
      arguments: '-WithUwpWrapper -CorePath "external/webrtc-uwp-sdk/webrtc/xplatform/webrtc/OUTPUT/webrtc/$(scriptPlatform)/${{parameters.buildArch}}/${{parameters.buildConfig}}/pdbs" -WrapperPath "external/webrtc-uwp-sdk/webrtc/windows/projects/msvc/Org.WebRtc.Universal/Build/Output/Org.WebRtc/${{parameters.buildConfig}}/${{parameters.buildArch}}" -WrapperGluePath "external/webrtc-uwp-sdk/webrtc/windows/projects/msvc/Org.WebRtc.WrapperGlue.Universal/Build/Output/Org.WebRtc.WrapperGlue/${{parameters.buildConfig}}/${{parameters.buildArch}}" -OutputPath $(Build.ArtifactStagingDirectory)/pdbs -BuildConfig ${{parameters.buildConfig}}'

  # List content of PDB packaging folder
  - powershell: |
      foreach ($f in $(Get-ChildItem -Path $(Build.ArtifactStagingDirectory)/pdbs -Recurse)) {
        Write-Host $f.FullName
      }
    displayName: 'List PDBs to package'
    timeoutInMinutes: 5

  # Publish PDBs for webrtc.lib as Universal Package (unlimited retention)
  - task: UniversalPackages@0
    displayName: 'Publish PDBs for webrtc.lib ($(buildTriple))'
    inputs:
      command: publish
      publishDirectory: '$(Build.ArtifactStagingDirectory)/pdbs'
      vstsFeedPublish: $(MRWebRTC_PdbFeed)
      vstsFeedPackagePublish: $(MRWebRTC_PdbPackageName)
      versionOption: custom
      versionPublish: $(MRWebRTC_PdbPackageVersion)
      packagePublishDescription: 'PDBs for MixedReality-WebRTC core (webrtc.lib) $(buildTriple)'
    timeoutInMinutes: 30
