
[features]
seeds = false
skip-lint = false
[programs.localnet]
workspace = "E7UrqiKK9etDpeBci1FjDps3tzwrySqkroyQvG2xNjcL"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
