language: node_js

# "node" (v16) is not supported by node-sass yet
# https://github.com/sass/node-sass/pull/3090
node_js:
  - "lts/*"

branches:
  only:
    - master

script:
  - npm run build
  - npm run test
  - npm run format
